import { useMemo } from 'react'

export default function AutoGeneratedFloorPlan({ units = [], selectedUnit, onSelectUnit }) {
  // Let's organize the units into a standard double-loaded corridor apartment structure:
  // Left side units, Right side units, and a central corridor structure.
  const structuredLayout = useMemo(() => {
    // Sort units to place them systematically
    const sorted = [...units].sort((a, b) => String(a.number).localeCompare(String(b.number), undefined, { numeric: true }))
    
    const leftUnits = []
    const rightUnits = []
    
    sorted.forEach((unit, idx) => {
      // Alternate left and right for balanced look
      if (idx % 2 === 0) {
        leftUnits.push(unit)
      } else {
        rightUnits.push(unit)
      }
    })
    
    return { leftUnits, rightUnits }
  }, [units])

  const getStatusColor = (status) => {
    const s = String(status || '').toLowerCase()
    if (s === 'available') return { bg: 'rgba(16, 185, 129, 0.15)', border: '#10b981', glow: 'rgba(16, 185, 129, 0.35)', color: '#a7f3d0' }
    if (s === 'sold') return { bg: 'rgba(239, 68, 68, 0.15)', border: '#ef4444', glow: 'transparent', color: '#fca5a5' }
    if (s === 'booked') return { bg: 'rgba(245, 158, 11, 0.15)', border: '#f59e0b', glow: 'rgba(245, 158, 11, 0.25)', color: '#fde68a' }
    return { bg: 'rgba(148, 163, 184, 0.1)', border: '#94a3b8', glow: 'transparent', color: '#e2e8f0' }
  }

  const renderUnitBlueprint = (unit) => {
    if (!unit) return null
    const isSelected = selectedUnit && String(selectedUnit.id) === String(unit.id)
    const { bg, border, glow, color } = getStatusColor(unit.status)
    const sqft = unit.areaSqft || Math.round((unit.areaSqft ?? 0)) || 1200
    const sqm = unit.areaSqm || Math.round(sqft / 10.764) || 111.5
    const bhk = unit.beds || 2

    return (
      <div
        key={unit.id}
        onClick={() => onSelectUnit && onSelectUnit(unit)}
        className="blueprint-unit-card"
        style={{
          border: `1.5px solid ${isSelected ? '#ffffff' : border}`,
          background: bg,
          boxShadow: isSelected ? '0 0 15px rgba(255, 255, 255, 0.4)' : (glow !== 'transparent' ? `0 0 10px ${glow}` : 'none'),
          transform: isSelected ? 'scale(1.02)' : 'scale(1)',
          transition: 'all 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
          cursor: 'pointer',
          borderRadius: '8px',
          padding: '1rem',
          position: 'relative',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          minHeight: '160px',
          color: '#ffffff',
          overflow: 'hidden'
        }}
      >
        {/* Dynamic Blueprint Room Grid Overlay */}
        <div style={{
          position: 'absolute',
          inset: 0,
          opacity: 0.15,
          border: '1px dashed #ffffff',
          margin: '4px',
          pointerEvents: 'none',
          display: 'grid',
          gridTemplateColumns: '1fr 1fr',
          gridTemplateRows: '1fr 1fr',
          gap: '2px'
        }}>
          <div style={{ borderRight: '1px dashed #ffffff', borderBottom: '1px dashed #ffffff', padding: '2px', fontSize: '8px' }}>Living</div>
          <div style={{ borderBottom: '1px dashed #ffffff', padding: '2px', fontSize: '8px' }}>Kitchen</div>
          <div style={{ borderRight: '1px dashed #ffffff', padding: '2px', fontSize: '8px' }}>Bath</div>
          <div style={{ padding: '2px', fontSize: '8px' }}>Bed</div>
        </div>

        {/* Balcony Indicator Box */}
        <div style={{
          position: 'absolute',
          bottom: '4px',
          right: '4px',
          border: '1px solid rgba(255,255,255,0.2)',
          padding: '2px 6px',
          fontSize: '0.65rem',
          borderRadius: '3px',
          background: 'rgba(255,255,255,0.05)',
          color: 'rgba(255,255,255,0.6)'
        }}>
          Balcony
        </div>

        {/* Content */}
        <div style={{ zIndex: 1 }}>
          <div style={{ fontSize: '1.25rem', fontWeight: 800, color: '#ffffff', letterSpacing: '0.05em' }}>
            {unit.number || `Unit ${unit.id}`}
          </div>
          <div style={{ fontSize: '0.75rem', color: color, fontWeight: '600', marginTop: '0.25rem' }}>
            {bhk} BHK Apartment
          </div>
        </div>

        <div style={{ zIndex: 1, marginTop: '2rem' }}>
          <div style={{ fontSize: '0.8rem', fontWeight: 700, color: 'rgba(255,255,255,0.9)' }}>
            {sqft.toLocaleString()} Sq Ft
          </div>
          <div style={{ fontSize: '0.7rem', color: 'rgba(255,255,255,0.6)' }}>
            {sqm.toFixed(1)} Sq M
          </div>
        </div>
      </div>
    )
  }

  return (
    <div style={{
      background: 'rgba(10, 20, 18, 0.4)',
      backdropFilter: 'blur(20px)',
      border: '1px solid rgba(16, 185, 129, 0.1)',
      boxShadow: '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
      borderRadius: '16px',
      padding: '2rem',
      color: '#ffffff',
      display: 'flex',
      flexDirection: 'column',
      gap: '2rem',
      width: '100%',
      minHeight: '600px'
    }}>
      {/* Title */}
      <div style={{ borderBottom: '1px solid rgba(16, 185, 129, 0.15)', paddingBottom: '1rem' }}>
        <h2 style={{ fontSize: '1.5rem', fontWeight: 800, margin: 0, letterSpacing: '0.05em' }}>FLOOR PLAN</h2>
        <p style={{ fontSize: '0.85rem', color: 'rgba(255,255,255,0.4)', margin: '4px 0 0 0' }}>Click on a unit to inspect room details, photos, and virtual tours</p>
      </div>

      {/* Main Floor Structure Layout */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: '1fr 120px 1fr',
        gap: '1.5rem',
        alignItems: 'stretch',
        flex: 1
      }}>
        {/* Left Side Units */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem', justifyContent: 'center' }}>
          {structuredLayout.leftUnits.map(renderUnitBlueprint)}
        </div>

        {/* Center Lift & Corridor Column */}
        <div style={{
          background: 'rgba(255, 255, 255, 0.02)',
          borderLeft: '2px solid rgba(255, 255, 255, 0.05)',
          borderRight: '2px solid rgba(255, 255, 255, 0.05)',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'space-around',
          padding: '2rem 0',
          position: 'relative'
        }}>
          {/* Corridor Label */}
          <div style={{
            transform: 'rotate(-90deg)',
            fontSize: '0.75rem',
            letterSpacing: '0.2em',
            color: 'rgba(255, 255, 255, 0.25)',
            fontWeight: 700,
            textTransform: 'uppercase'
          }}>
            Corridor
          </div>

          {/* Elevator shafts visual */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', width: '100%', alignItems: 'center' }}>
            <div style={{
              width: '60px',
              height: '60px',
              border: '2px dashed rgba(255,255,255,0.1)',
              borderRadius: '6px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: 'rgba(255,255,255,0.15)',
              fontSize: '0.65rem',
              fontWeight: 700
            }}>
              LIFT
            </div>
            <div style={{
              width: '60px',
              height: '60px',
              border: '2px dashed rgba(255,255,255,0.1)',
              borderRadius: '6px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: 'rgba(255,255,255,0.15)',
              fontSize: '0.65rem',
              fontWeight: 700
            }}>
              LIFT
            </div>
          </div>

          {/* Stairs visual */}
          <div style={{
            width: '70px',
            height: '100px',
            border: '2px solid rgba(255,255,255,0.05)',
            backgroundImage: 'repeating-linear-gradient(0deg, transparent, transparent 10px, rgba(255,255,255,0.05) 10px, rgba(255,255,255,0.05) 12px)',
            borderRadius: '4px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: 'rgba(255,255,255,0.15)',
            fontSize: '0.65rem',
            fontWeight: 700
          }}>
            STAIRS
          </div>
        </div>

        {/* Right Side Units */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem', justifyContent: 'center' }}>
          {structuredLayout.rightUnits.map(renderUnitBlueprint)}
        </div>
      </div>

      {/* Legend Block */}
      <div style={{
        display: 'flex',
        gap: '2rem',
        justifyContent: 'center',
        borderTop: '1px solid rgba(255, 255, 255, 0.05)',
        paddingTop: '1rem',
        fontSize: '0.85rem'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <div style={{ width: '12px', height: '12px', borderRadius: '3px', background: 'rgba(16, 185, 129, 0.2)', border: '1px solid #10b981', boxShadow: '0 0 8px rgba(16, 185, 129, 0.4)' }} />
          <span style={{ color: 'rgba(255,255,255,0.7)', fontWeight: '600' }}>Available</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <div style={{ width: '12px', height: '12px', borderRadius: '3px', background: 'rgba(245, 158, 11, 0.2)', border: '1px solid #f59e0b', boxShadow: '0 0 8px rgba(245, 158, 11, 0.3)' }} />
          <span style={{ color: 'rgba(255,255,255,0.7)', fontWeight: '600' }}>Booked</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <div style={{ width: '12px', height: '12px', borderRadius: '3px', background: 'rgba(239, 68, 68, 0.2)', border: '1px solid #ef4444' }} />
          <span style={{ color: 'rgba(255,255,255,0.7)', fontWeight: '600' }}>Sold</span>
        </div>
      </div>
    </div>
  )
}
