import { useState, useEffect, useMemo } from 'react'
import AutoGeneratedFloorPlan from './AutoGeneratedFloorPlan'
import ImagePlotMapView from './ImagePlotMapView'
import Custom3DWalkthrough from './Custom3DWalkthrough'
import { createPortal } from 'react-dom'
import { useCreateLeadMutation } from '../api/apiSlice'

export default function PremiumBuyerBuildingView({ layout }) {
  const [selectedUnit, setSelectedUnit] = useState(null)
  const [activeImageIdx, setActiveImageIdx] = useState(0)
  const [walkthroughOpen, setWalkthroughOpen] = useState(false)
  const [interestModalOpen, setInterestModalOpen] = useState(false)
  const [isFloorDropdownOpen, setIsFloorDropdownOpen] = useState(false)
  const [currentStep, setCurrentStep] = useState('facade') // 'facade' or 'floorplan'
  const [facadeAspectRatio, setFacadeAspectRatio] = useState(16 / 10)

  const handleFacadeImageLoad = (e) => {
    const img = e.target
    if (img?.naturalWidth && img?.naturalHeight) {
      setFacadeAspectRatio(img.naturalWidth / img.naturalHeight)
    }
  }
  
  // Lead submission states
  const [customerName, setCustomerName] = useState('')
  const [contactNumber, setContactNumber] = useState('')
  const [customerEmail, setCustomerEmail] = useState('')
  const [customerMessage, setCustomerMessage] = useState('')
  const [submitted, setSubmitted] = useState(false)
  const [createLead, { isLoading: submittingLead }] = useCreateLeadMutation()
  const [leadError, setLeadError] = useState('')

  useEffect(() => {
    if (submitted) {
      const timer = setTimeout(() => {
        setSubmitted(false)
      }, 5000)
      return () => clearTimeout(timer)
    }
    return undefined
  }, [submitted])

  const sortedFloors = useMemo(() => {
    const floors = layout?.building?.floors || []
    return [...floors].sort((a, b) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0))
  }, [layout])

  const [selectedFloorId, setSelectedFloorId] = useState(() => {
    return sortedFloors[0]?.id || null
  })

  const currentFloor = useMemo(() => {
    return sortedFloors.find(f => f.id === selectedFloorId) || sortedFloors[0]
  }, [sortedFloors, selectedFloorId])

  // Get units for current floor
  // If real plotted units exist, use them. Otherwise, auto-generate from floor configurations.
  const floorUnits = useMemo(() => {
    const plottedUnits = (layout?.plots || []).filter(p => String(p.floor) === String(selectedFloorId))
    if (plottedUnits.length > 0) return plottedUnits

    // Auto-generate units from floor configurations when no plots are manually placed
    const floor = (layout?.building?.floors || []).find(f => f.id === selectedFloorId)
    if (!floor || !floor.configurations?.length) return []

    return floor.configurations.map((cfg, idx) => ({
      id: `${selectedFloorId}-${cfg.id}`,
      number: `${(floor.sortOrder ?? 0) + 1}${String.fromCharCode(65 + idx)}`,
      floor: selectedFloorId,
      configId: cfg.id,
      tower: layout?.building?.towers?.[0]?.id || 'A',
      beds: parseInt(cfg.label) || (cfg.id?.match(/(\d+)bhk/i)?.[1]) || 2,
      areaSqft: cfg.areaSqft || 0,
      areaSqm: cfg.areaSqm || 0,
      facing: 'East',
      status: 'Available',
      pricePerSqft: cfg.pricePerSqft || 0,
      estimatedPrice: (cfg.areaSqft || 0) * (cfg.pricePerSqft || 0),
      label: cfg.label || cfg.id,
    }))
  }, [layout, selectedFloorId])

  // Extract media assets for room types. Only returns real uploaded data.
  const getRoomMedia = (unit) => {
    if (!unit) return { images: [], walkthroughUrl: '', rooms: [] }
    
    const apiBase = import.meta.env.VITE_API_URL || ''
    
    // Find matching configuration on this floor
    const floor = (layout?.building?.floors || []).find(f => String(f.id) === String(unit.floor))
    const config = floor?.configurations?.find(c => 
      c.id === unit.configId || 
      String(c.beds) === String(unit.beds) || 
      (c.label && c.label.toLowerCase().includes(`${unit.beds} bhk`)) ||
      (c.id && c.id.toLowerCase().includes(`${unit.beds}bhk`))
    )

    const configImages = (config?.images || []).map(img => 
      img.startsWith('http') || img.startsWith('data:') || img.startsWith('blob:')
        ? img
        : `${apiBase}/uploads/${img}`
    )

    const roomsMap = unit.rooms || config?.rooms || {}
    const roomKeys = Object.keys(roomsMap).filter(k => !!roomsMap[k])
    
    let generatedRooms = []
    let roomImages = []

    if (roomKeys.length > 0) {
      const getRoomName = (id) => {
        if (id === 'hall') return 'Living Room'
        if (id === 'kitchen') return 'Kitchen'
        if (id === 'bathroom') return 'Bathroom'
        if (id === 'balcony') return 'Balcony'
        if (id.startsWith('bedroom')) {
          const num = id.replace('bedroom', '')
          return `Bedroom ${num}`
        }
        return id.toUpperCase()
      }

      roomKeys.forEach((key, index) => {
        const path = roomsMap[key]
        let fullPath = path
        if (!path.startsWith('http') && !path.startsWith('data:') && !path.startsWith('blob:')) {
          if (path.startsWith('/uploads')) {
             fullPath = `${apiBase}${path}`
          } else {
             fullPath = `${apiBase}/uploads/${path}`
          }
        }
        
        roomImages.push(fullPath)

        const hotspots = []
        // Link all rooms back to Hall (Living Room)
        if (key !== 'hall' && roomsMap['hall']) {
          hotspots.push({ targetRoomId: 'hall', x: '45%', y: '80%', label: 'Go to Living Room' })
        }
        
        // Link Hall to other rooms
        if (key === 'hall') {
          let yOffset = 35
          roomKeys.forEach(otherKey => {
            if (otherKey !== 'hall' && roomsMap[otherKey]) {
              hotspots.push({ 
                targetRoomId: otherKey, 
                x: '50%', 
                y: `${yOffset}%`, 
                label: `Go to ${getRoomName(otherKey)}` 
              })
              yOffset += 12
            }
          })
        } else {
          // Link non-hall rooms sequentially
          const nextIndex = (index + 1) % roomKeys.length
          const nextKey = roomKeys[nextIndex]
          if (nextKey !== 'hall' && nextKey !== key && roomsMap[nextKey]) {
            hotspots.push({ 
              targetRoomId: nextKey, 
              x: '80%', 
              y: '50%', 
              label: `Go to ${getRoomName(nextKey)}` 
            })
          }
        }

        generatedRooms.push({
          id: key,
          name: getRoomName(key),
          imagePath: fullPath,
          hotspots
        })
      })
    }

    return {
      images: unit.images || (roomImages.length > 0 ? roomImages : (configImages.length > 0 ? configImages : [])),
      walkthroughUrl: unit.walkthroughUrl || '',
      rooms: generatedRooms.length > 0 ? generatedRooms : []
    }
  }


  const selectedUnitMedia = useMemo(() => {
    return getRoomMedia(selectedUnit)
  }, [selectedUnit])

  const allUnits = useMemo(() => {
    const plots = layout?.plots || []
    if (plots.length > 0) return plots
    
    const generated = []
    const floors = layout?.building?.floors || []
    floors.forEach(f => {
      const floorId = f.id
      const configs = f.configurations || []
      configs.forEach((cfg, idx) => {
        generated.push({
          id: `${floorId}-${cfg.id}`,
          floor: floorId,
          status: 'Available',
        })
      })
    })
    return generated
  }, [layout])

  const overallStats = useMemo(() => {
    let available = 0
    let booked = 0
    let sold = 0
    allUnits.forEach(u => {
      const status = (u.status || 'Available').toLowerCase()
      if (status === 'available') available++
      else if (status === 'booked') booked++
      else if (status === 'sold') sold++
    })
    return { total: allUnits.length, available, booked, sold }
  }, [allUnits])

  const floorStats = useMemo(() => {
    let available = 0
    let booked = 0
    let sold = 0
    floorUnits.forEach(u => {
      const status = (u.status || 'Available').toLowerCase()
      if (status === 'available') available++
      else if (status === 'booked') booked++
      else if (status === 'sold') sold++
    })
    return { total: floorUnits.length, available, booked, sold }
  }, [floorUnits])

  const allFloorsStats = useMemo(() => {
    const stats = {}
    sortedFloors.forEach(f => {
      const plottedUnits = (layout?.plots || []).filter(p => String(p.floor) === String(f.id))
      let units = []
      if (plottedUnits.length > 0) {
        units = plottedUnits
      } else if (f.configurations?.length) {
        units = f.configurations.map((cfg, idx) => ({
          status: cfg.status || 'Available'
        }))
      }
      
      const available = units.filter(u => (u.status || 'Available').toLowerCase() === 'available').length
      const booked = units.filter(u => (u.status || '').toLowerCase() === 'booked' || (u.status || '').toLowerCase() === 'pending').length
      const sold = units.filter(u => (u.status || '').toLowerCase() === 'sold').length
      
      let color = '#ef4444' // red
      if (available > 0) color = '#10b981' // green
      else if (booked > 0) color = '#f59e0b' // yellow
      
      stats[f.id] = {
        total: units.length,
        available,
        booked,
        sold,
        color
      }
    })
    return stats
  }, [sortedFloors, layout])

  const formatPrice = (price) => {
    if (!price || price <= 0) return 'Contact for Price'
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 0
    }).format(price)
  }

  const handleLeadSubmit = async (e) => {
    e.preventDefault()
    if (!customerName.trim() || !contactNumber.trim() || !customerEmail.trim()) {
      setLeadError('Please fill in all details.')
      return
    }
    setLeadError('')
    try {
      await createLead({
        layoutId: layout.id,
        plotId: selectedUnit.id,
        customerName: customerName.trim(),
        contactNumber: contactNumber.trim(),
        customerEmail: customerEmail.trim(),
        metadata: JSON.stringify({ message: customerMessage.trim(), inquiryType: 'Booking' })
      }).unwrap()
      setSubmitted(true)
      setInterestModalOpen(false)
      // Clear inputs
      setCustomerName('')
      setContactNumber('')
      setCustomerEmail('')
      setCustomerMessage('')
    } catch (err) {
      setLeadError(err.data?.error || err.message || 'Failed to submit request.')
    }
  }

  // Builder info details
  const phaseInfo = layout?.phaseInfo || {}
  const builderName = layout?.owner?.name || layout?.builderName || phaseInfo.builderName || 'Luxury Developments Corp.'
  const companyName = layout?.owner?.companyName || layout?.companyName || phaseInfo.companyName || 'Aurora Developments'
  const builderPhone = layout?.owner?.phone || phaseInfo.phone || phaseInfo.contactPhone || '+91 98765 43210'
  const builderWhatsapp = layout?.owner?.phone 
    ? layout.owner.phone.replace(/[^0-9]/g, '') 
    : (phaseInfo.whatsapp || '919876543210')
  const builderEmail = layout?.owner?.email || phaseInfo.email || 'sales@auroradevelopments.com'
  const builderExperience = layout?.owner?.experience != null ? layout.owner.experience : null
  const builderProjects = layout?.owner?.projectsDelivered != null ? layout.owner.projectsDelivered : null
  const builderRera = layout?.owner?.rera || phaseInfo.rera || null

  const apiBase = import.meta.env.VITE_API_URL || ''
  const buildingBanner = layout?.imagePath 
    ? (layout.imagePath.startsWith('http') || layout.imagePath.startsWith('data:') || layout.imagePath.startsWith('blob:')
        ? layout.imagePath
        : `${apiBase}/uploads/${layout.imagePath}`)
    : 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80';

  return (
    <div className="premium-buyer-container">
      {/* Dynamic Style injection for premium looks and responsiveness */}
      <style>{`
        /* Global Redesign Overrides */
        .premium-buyer-container {
          display: flex;
          height: 100vh;
          width: 100%;
          background: #f8fafc;
          overflow: hidden;
          color: #0f172a;
          font-family: 'Inter', system-ui, -apple-system, sans-serif;
        }

        .premium-buyer-main {
          flex: 1;
          height: 100%;
          padding: 2rem;
          overflow-y: auto;
          display: flex;
          flex-direction: column;
          gap: 2rem;
        }

        .premium-buyer-sidebar {
          width: 440px;
          height: 100%;
          background: rgba(255, 255, 255, 0.85);
          backdrop-filter: blur(24px);
          -webkit-backdrop-filter: blur(24px);
          border-left: 1px solid rgba(15, 23, 42, 0.08);
          display: flex;
          flex-direction: column;
          box-shadow: -10px 0 35px rgba(15, 23, 42, 0.03);
          overflow-y: auto;
        }

        /* Responsive Layout Settings */
        @media (max-width: 1023px) {
          .premium-buyer-container {
            flex-direction: column;
            height: auto;
            overflow: visible;
          }
          .premium-buyer-main {
            height: auto;
            padding: 1.25rem;
            overflow-y: visible;
            gap: 1.5rem;
          }
          .premium-buyer-sidebar {
            width: 100%;
            height: auto;
            border-left: none;
            border-top: 1px solid rgba(15, 23, 42, 0.08);
            overflow-y: visible;
            box-shadow: none;
          }
        }

        /* Banner styling */
        .premium-hero-banner {
          position: relative;
          border-radius: 24px;
          background-size: cover;
          background-position: center;
          padding: 1rem 1.75rem;
          color: #ffffff;
          box-shadow: 0 10px 25px rgba(15, 23, 42, 0.05);
          display: flex;
          align-items: center;
          min-height: 90px;
          transition: all 0.4s cubic-bezier(0.16, 1, 0.3, 1);
          z-index: 20;
        }
        
        .premium-hero-banner:hover {
          box-shadow: 0 15px 30px rgba(15, 23, 42, 0.09);
        }

        /* Interactive Map Highlight Overrides */
        .image-plot-overlay-shape {
          transition: fill 0.3s cubic-bezier(0.16, 1, 0.3, 1), stroke 0.3s cubic-bezier(0.16, 1, 0.3, 1), stroke-width 0.3s cubic-bezier(0.16, 1, 0.3, 1) !important;
        }
        
        .image-plot-overlay-shape.status-available {
          stroke: #10b981 !important;
          fill: rgba(16, 185, 129, 0.14) !important;
          stroke-width: 0.6px !important;
        }
        .image-plot-overlay-shape.status-available:hover {
          fill: rgba(16, 185, 129, 0.26) !important;
          stroke-width: 1.2px !important;
        }
        .image-plot-overlay-shape.status-available.selected {
          fill: rgba(16, 185, 129, 0.34) !important;
          stroke: #10b981 !important;
          stroke-width: 2px !important;
          filter: drop-shadow(0 0 6px rgba(16, 185, 129, 0.4));
        }

        .image-plot-overlay-shape.status-booked {
          stroke: #f59e0b !important;
          fill: rgba(245, 158, 11, 0.15) !important;
          stroke-width: 0.6px !important;
        }
        .image-plot-overlay-shape.status-booked:hover {
          fill: rgba(245, 158, 11, 0.26) !important;
          stroke-width: 1.2px !important;
        }
        .image-plot-overlay-shape.status-booked.selected {
          fill: rgba(245, 158, 11, 0.34) !important;
          stroke: #f59e0b !important;
          stroke-width: 2px !important;
          filter: drop-shadow(0 0 6px rgba(245, 158, 11, 0.4));
        }

        .image-plot-overlay-shape.status-sold {
          stroke: #ef4444 !important;
          fill: rgba(239, 68, 68, 0.12) !important;
          stroke-width: 0.6px !important;
        }
        .image-plot-overlay-shape.status-sold:hover {
          fill: rgba(239, 68, 68, 0.22) !important;
          stroke-width: 1.2px !important;
        }
        .image-plot-overlay-shape.status-sold.selected {
          fill: rgba(239, 68, 68, 0.3) !important;
          stroke: #ef4444 !important;
          stroke-width: 2px !important;
          filter: drop-shadow(0 0 6px rgba(239, 68, 68, 0.4));
        }

        .overlay-label {
          background: rgba(15, 23, 42, 0.8) !important;
          backdrop-filter: blur(4px);
          border: 1px solid rgba(255, 255, 255, 0.15);
          color: #ffffff !important;
          font-size: 0.725rem !important;
          font-weight: 700 !important;
          padding: 3px 7px !important;
          border-radius: 6px !important;
          box-shadow: 0 2px 4px rgba(0,0,0,0.08);
          pointer-events: none;
        }

        /* Chips & Dropdown */
        .luxury-select-wrapper::after {
          content: '▼';
          font-size: 0.75rem;
          color: #ffffff;
          position: absolute;
          right: 1.25rem;
          top: 50%;
          transform: translateY(-50%) scale(0.9);
          pointer-events: none;
          opacity: 0.8;
        }
        .luxury-select {
          background: rgba(255, 255, 255, 0.15);
          backdrop-filter: blur(12px);
          -webkit-backdrop-filter: blur(12px);
          border: 1px solid rgba(255, 255, 255, 0.25);
          color: #ffffff;
          padding: 0.65rem 2.5rem 0.65rem 1.25rem;
          border-radius: 30px;
          outline: none;
          font-size: 0.95rem;
          font-weight: 600;
          cursor: pointer;
          appearance: none;
          transition: all 0.3s ease;
        }
        .luxury-select:hover {
          background: rgba(255, 255, 255, 0.25);
          border-color: rgba(255, 255, 255, 0.45);
        }

        .stat-chip-pill {
          display: inline-flex;
          align-items: center;
          gap: 0.45rem;
          padding: 0.45rem 0.85rem;
          border-radius: 30px;
          font-size: 0.825rem;
          font-weight: 600;
          background: rgba(255, 255, 255, 0.1);
          backdrop-filter: blur(10px);
          -webkit-backdrop-filter: blur(10px);
          border: 1px solid rgba(255, 255, 255, 0.18);
          color: #ffffff;
          transition: all 0.2s ease;
        }
        .stat-chip-pill:hover {
          background: rgba(255, 255, 255, 0.18);
          transform: translateY(-1px);
        }
        .stat-chip-pill .dot {
          width: 6px;
          height: 6px;
          border-radius: 50%;
        }
        .stat-chip-pill.total .dot { background: #e2e8f0; }
        .stat-chip-pill.available .dot { background: #10b981; }
        .stat-chip-pill.booked .dot { background: #f59e0b; }
        .stat-chip-pill.sold .dot { background: #ef4444; }

        /* Media and CTAs */
        .carousel-thumbnails::-webkit-scrollbar {
          display: none;
        }
        .thumbnail-btn {
          transition: all 0.25s cubic-bezier(0.16, 1, 0.3, 1);
        }
        .thumbnail-btn:hover {
          transform: scale(1.04);
          border-color: #10b981 !important;
        }

        .premium-3d-button:hover {
          transform: translateY(-2px);
          box-shadow: 0 10px 25px rgba(16, 185, 129, 0.3);
          background: linear-gradient(135deg, #059669 0%, #047857 100%) !important;
        }
        .premium-3d-button:hover svg {
          transform: scale(1.15) translateX(2px);
        }
        .premium-3d-button:active {
          transform: translateY(1px);
        }

        /* Contact card hover animations */
        .builder-btn-wa:hover {
          background: #128C7E !important;
          transform: translateY(-1px);
          box-shadow: 0 4px 8px rgba(37, 211, 102, 0.25) !important;
        }
        .builder-btn-call:hover {
          background: #f8fafc !important;
          border-color: #cbd5e1 !important;
          transform: translateY(-1px);
        }
        .builder-btn-interest:hover {
          background: #d1fae5 !important;
          transform: translateY(-1px);
          box-shadow: 0 4px 8px rgba(16, 185, 129, 0.15) !important;
        }

        /* Modal transitions */
        @keyframes fade-in {
          from { opacity: 0; }
          to { opacity: 1; }
        }
        @keyframes scale-up {
          from { transform: scale(0.96); opacity: 0; }
          to { transform: scale(1); opacity: 1; }
        }
        @keyframes slide-down {
          from { transform: translate(-50%, -20px); opacity: 0; }
          to { transform: translate(-50%, 0); opacity: 1; }
        }
        @keyframes bounce {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-4px); }
        }

        /* Status Badge for Details */
        .status-badge-luxury {
          font-size: 0.75rem;
          font-weight: 700;
          padding: 0.35rem 0.75rem;
          border-radius: 20px;
          text-transform: uppercase;
          letter-spacing: 0.05em;
          display: inline-flex;
          align-items: center;
        }
        .status-badge-luxury.available {
          background: #ecfdf5;
          color: #10b981;
          border: 1px solid #a7f3d0;
        }
        .status-badge-luxury.booked {
          background: #fffbeb;
          color: #f59e0b;
          border: 1px solid #fde68a;
        }
        .status-badge-luxury.sold {
          background: #fef2f2;
          color: #ef4444;
          border: 1px solid #fecaca;
        }

        .spec-item {
          display: flex;
          flex-direction: column;
          gap: 0.25rem;
        }
        .spec-label {
          font-size: 0.75rem;
          font-weight: 600;
          color: #64748b;
          text-transform: uppercase;
          letter-spacing: 0.05em;
        }
        .spec-val {
          font-size: 1.05rem;
          font-weight: 700;
          color: #0f172a;
        }
      `}</style>

      {/* LEFT CONTENT VIEW - Hero Section and Interactive Plan */}
      {currentStep === 'facade' ? (
        <div className="premium-buyer-main">
          {/* Facade Step Main Card */}
          <div style={{
            display: 'flex',
            gap: '2rem',
            flex: 1,
            flexDirection: 'row',
            flexWrap: 'wrap'
          }}>
            {/* Facade Model Interactive Viewer */}
            <div style={{
              flex: '1.6 1 400px',
              background: '#ffffff',
              borderRadius: '24px',
              border: '1px solid #e2e8f0',
              boxShadow: '0 10px 30px rgba(15, 23, 42, 0.02)',
              position: 'relative',
              overflow: 'hidden',
              display: 'flex',
              flexDirection: 'column',
              minHeight: '500px'
            }}>
              <div style={{
                padding: '1.5rem',
                borderBottom: '1px solid #f1f5f9',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                flexWrap: 'wrap',
                gap: '1rem'
              }}>
                <div>
                  <h1 style={{ fontSize: '1.4rem', fontWeight: 800, margin: 0, color: '#0f172a' }}>
                    {layout?.name || 'Building Layout'}
                  </h1>
                  <p style={{ margin: '4px 0 0 0', fontSize: '0.85rem', color: '#64748b', fontWeight: 500 }}>
                    Select a floor on the building model or use the floor stack to explore floor plans.
                  </p>
                </div>
              </div>

              {/* Building Facade Graphic Wrapper */}
              <div style={{ flex: 1, position: 'relative', overflow: 'hidden', minHeight: '450px', background: '#0a0f1d', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <div style={{
                  position: 'relative',
                  width: '100%',
                  aspectRatio: facadeAspectRatio,
                  maxHeight: '100%',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center'
                }}>
                  <img 
                    onLoad={handleFacadeImageLoad}
                    src={layout?.building?.facadeImagePath ? `${import.meta.env.VITE_API_URL || ''}/uploads/${layout.building.facadeImagePath}` : 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80'} 
                    alt="Building Facade Model" 
                    style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'fill', display: 'block' }} 
                  />

                  {/* SVG Polygon Layers on Facade */}
                  <svg
                    viewBox="0 0 100 100"
                    preserveAspectRatio="none"
                    style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', zIndex: 10 }}
                  >
                    {sortedFloors.map(f => {
                      const points = layout?.overlayConfig?.facadeByFloor?.[f.id]?.points
                      if (!points || !points.length) return null
                      const ptsStr = points.map(([x, y]) => `${x},${y}`).join(' ')
                      const stats = allFloorsStats[f.id] || { available: 0, booked: 0, sold: 0 }
                      
                      let statusClass = 'available'
                      if (stats.available > 0) {
                        statusClass = 'available'
                      } else if (stats.booked > 0) {
                        statusClass = 'booked'
                      } else {
                        statusClass = 'sold'
                      }

                      return (
                        <polygon
                          key={f.id}
                          points={ptsStr}
                          onClick={() => {
                            setSelectedFloorId(f.id)
                            setSelectedUnit(null)
                            setCurrentStep('floorplan')
                          }}
                          style={{
                            cursor: 'pointer',
                            transition: 'all 0.3s ease',
                          }}
                          className={`image-plot-overlay-shape status-${statusClass}`}
                        />
                      )
                    })}
                  </svg>

                  {/* Float Centered Label Markers */}
                  <div style={{ position: 'absolute', inset: 0, pointerEvents: 'none', zIndex: 20 }}>
                    {sortedFloors.map(f => {
                      const points = layout?.overlayConfig?.facadeByFloor?.[f.id]?.points
                      if (!points || !points.length) return null
                      const cx = points.reduce((s, [x]) => s + x, 0) / points.length
                      const cy = points.reduce((s, [, y]) => s + y, 0) / points.length
                      const stats = allFloorsStats[f.id] || { color: '#10b981' }

                      return (
                        <div
                          key={f.id}
                          style={{
                            position: 'absolute',
                            left: `${cx}%`,
                            top: `${cy}%`,
                            transform: 'translate(-50%, -50%)',
                            background: 'rgba(15, 23, 42, 0.95)',
                            backdropFilter: 'blur(8px)',
                            border: `1.5px solid ${stats.color}`,
                            color: '#ffffff',
                            borderRadius: '8px',
                            padding: '6px 12px',
                            fontSize: '0.725rem',
                            fontWeight: '800',
                            boxShadow: '0 4px 12px rgba(0, 0, 0, 0.35)',
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            whiteSpace: 'nowrap'
                          }}
                        >
                          <span style={{ color: '#ffffff' }}>{f.label || `Floor ${(f.sortOrder ?? 0) + 1}`}</span>
                        </div>
                      )
                    })}
                  </div>
                </div>
              </div>
            </div>

            {/* Facade Side Stack Selection */}
            <div style={{
              flex: '1 1 300px',
              background: '#ffffff',
              borderRadius: '24px',
              border: '1px solid #e2e8f0',
              boxShadow: '0 10px 30px rgba(15, 23, 42, 0.02)',
              padding: '1.5rem',
              display: 'flex',
              flexDirection: 'column',
              gap: '1rem',
              maxHeight: '600px',
              overflowY: 'auto'
            }} className="custom-scrollbar">
              <h2 style={{ fontSize: '1rem', fontWeight: 800, color: '#0f172a', margin: '0 0 0.5rem 0', textTransform: 'uppercase', letterSpacing: '0.08em' }}>
                Building Floors
              </h2>
              
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                {[...sortedFloors].reverse().map(f => {
                  const stats = allFloorsStats[f.id] || { total: 0, available: 0, booked: 0, sold: 0, color: '#ef4444' }
                  return (
                    <button
                      key={f.id}
                      onClick={() => {
                        setSelectedFloorId(f.id)
                        setSelectedUnit(null)
                        setCurrentStep('floorplan')
                      }}
                      style={{
                        background: '#f8fafc',
                        border: '1px solid #e2e8f0',
                        borderLeft: `4px solid ${stats.color}`,
                        borderRadius: '12px',
                        padding: '1.2rem',
                        cursor: 'pointer',
                        textAlign: 'left',
                        display: 'flex',
                        justifyContent: 'space-between',
                        alignItems: 'center',
                        transition: 'all 0.25s cubic-bezier(0.16, 1, 0.3, 1)',
                        width: '100%',
                        boxShadow: '0 2px 4px rgba(0,0,0,0.01)'
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.background = '#ffffff';
                        e.currentTarget.style.borderColor = '#cbd5e1';
                        e.currentTarget.style.transform = 'translateY(-2px)';
                        e.currentTarget.style.boxShadow = '0 6px 16px rgba(15, 23, 42, 0.05)';
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.background = '#f8fafc';
                        e.currentTarget.style.borderColor = '#e2e8f0';
                        e.currentTarget.style.transform = 'translateY(0)';
                        e.currentTarget.style.boxShadow = '0 2px 4px rgba(0,0,0,0.01)';
                      }}
                    >
                      <div>
                        <h4 style={{ margin: 0, fontSize: '0.95rem', fontWeight: '800', color: '#1e293b' }}>
                          {f.label || `Floor ${(f.sortOrder ?? 0) + 1}`}
                        </h4>
                        <span style={{ fontSize: '0.75rem', color: '#94a3b8', fontWeight: '600' }}>
                          Total Units: {stats.total}
                        </span>
                      </div>
                      
                      {/* Color-Coded Counts */}
                      <div style={{ display: 'flex', gap: '0.4rem' }}>
                        <span style={{ fontSize: '0.7rem', fontWeight: '700', padding: '0.25rem 0.5rem', borderRadius: '8px', background: '#ecfdf5', color: '#059669' }}>
                          {stats.available} Available
                        </span>
                        <span style={{ fontSize: '0.7rem', fontWeight: '700', padding: '0.25rem 0.5rem', borderRadius: '8px', background: '#fffbeb', color: '#d97706' }}>
                          {stats.booked} Booked
                        </span>
                        <span style={{ fontSize: '0.7rem', fontWeight: '700', padding: '0.25rem 0.5rem', borderRadius: '8px', background: '#fef2f2', color: '#dc2626' }}>
                          {stats.sold} Sold
                        </span>
                      </div>
                    </button>
                  )
                })}
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div className="premium-buyer-main">
          {/* Floor Plan Card */}
          <div style={{
            background: '#ffffff',
            borderRadius: '24px',
            border: '1px solid #e2e8f0',
            boxShadow: '0 10px 30px rgba(15, 23, 42, 0.02)',
            flex: 1,
            position: 'relative',
            overflow: 'hidden',
            minHeight: '520px',
            display: 'flex',
            flexDirection: 'column'
          }}>
            {/* Interactive plan banner and legend */}
            <div style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              padding: '1.25rem 1.5rem',
              borderBottom: '1px solid #f1f5f9',
              background: '#ffffff',
              flexWrap: 'wrap',
              gap: '1rem',
              zIndex: 10
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', flexWrap: 'wrap' }}>
                <button
                  onClick={() => {
                    setCurrentStep('facade')
                    setSelectedUnit(null)
                  }}
                  style={{
                    background: 'transparent',
                    border: '1px solid #cbd5e1',
                    borderRadius: '8px',
                    padding: '0.4rem 0.8rem',
                    fontSize: '0.85rem',
                    fontWeight: '600',
                    color: '#475569',
                    cursor: 'pointer',
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: '0.4rem',
                    transition: 'all 0.2s'
                  }}
                  onMouseEnter={(e) => { e.currentTarget.style.background = '#f1f5f9'; e.currentTarget.style.borderColor = '#94a3b8'; }}
                  onMouseLeave={(e) => { e.currentTarget.style.background = 'transparent'; e.currentTarget.style.borderColor = '#cbd5e1'; }}
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>
                  Building Model
                </button>

                <h1 style={{
                  fontSize: '1.25rem',
                  fontWeight: 800,
                  margin: 0,
                  color: '#0f172a',
                  letterSpacing: '-0.01em',
                }}>
                  {layout?.name || 'Building Layout'}
                </h1>
                
                <div style={{ width: '1px', height: '24px', background: '#e2e8f0' }} />
                
                {/* Floor picker dropdown styled luxury */}
                <div className="luxury-select-wrapper" style={{ position: 'relative', zIndex: 9999 }}>
                  <div 
                    className="luxury-select" 
                    style={{ 
                      padding: '0.5rem 2rem 0.5rem 1rem', 
                      fontSize: '0.85rem', 
                      display: 'flex', 
                      alignItems: 'center',
                      minWidth: '120px',
                      userSelect: 'none',
                      background: '#f8fafc',
                      border: '1px solid #e2e8f0',
                      borderRadius: '8px',
                      fontWeight: 600,
                      color: '#334155',
                      cursor: 'pointer'
                    }}
                    onClick={() => setIsFloorDropdownOpen(!isFloorDropdownOpen)}
                  >
                    {currentFloor?.label || `Floor ${(currentFloor?.sortOrder ?? 0) + 1}`}
                    <svg style={{ position: 'absolute', right: '0.75rem' }} width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="6 9 12 15 18 9"></polyline></svg>
                  </div>
                  
                  {isFloorDropdownOpen && (
                    <div style={{
                      position: 'absolute',
                      top: '100%',
                      left: 0,
                      marginTop: '0.5rem',
                      width: '100%',
                      minWidth: '150px',
                      background: '#ffffff',
                      borderRadius: '12px',
                      boxShadow: '0 10px 25px rgba(0,0,0,0.1)',
                      overflowY: 'auto',
                      maxHeight: '250px',
                      zIndex: 99999,
                      border: '1px solid #e2e8f0',
                      display: 'flex',
                      flexDirection: 'column',
                      padding: '0.5rem 0'
                    }}>
                      {sortedFloors.map(f => (
                        <button
                          key={f.id}
                          onClick={() => {
                            setSelectedFloorId(f.id)
                            setSelectedUnit(null)
                            setIsFloorDropdownOpen(false)
                          }}
                          style={{
                            padding: '0.75rem 1.25rem',
                            background: selectedFloorId === f.id ? '#f8fafc' : 'transparent',
                            border: 'none',
                            textAlign: 'left',
                            width: '100%',
                            cursor: 'pointer',
                            color: selectedFloorId === f.id ? '#10b981' : '#334155',
                            fontWeight: selectedFloorId === f.id ? '700' : '500',
                            fontSize: '0.9rem',
                            transition: 'background 0.2s ease',
                            outline: 'none'
                          }}
                          onMouseEnter={(e) => {
                            if (selectedFloorId !== f.id) e.target.style.background = '#f1f5f9'
                          }}
                          onMouseLeave={(e) => {
                            if (selectedFloorId !== f.id) e.target.style.background = 'transparent'
                          }}
                        >
                          {f.label || `Floor ${(f.sortOrder ?? 0) + 1}`}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              </div>
              
              {/* Building Statistics Chips */}
              <div style={{ display: 'flex', gap: '0.6rem', alignItems: 'center', flexWrap: 'wrap' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.35rem', fontSize: '0.75rem', fontWeight: 700, color: '#475569', background: '#f8fafc', padding: '0.4rem 0.75rem', borderRadius: '20px', border: '1px solid #e2e8f0' }}>
                  <span>{overallStats.total} Units</span>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.35rem', fontSize: '0.75rem', fontWeight: 700, color: '#047857', background: '#ecfdf5', padding: '0.4rem 0.75rem', borderRadius: '20px', border: '1px solid #a7f3d0' }}>
                  <span style={{ width: '6px', height: '6px', borderRadius: '50%', background: '#10b981' }} />
                  <span>{overallStats.available} Available</span>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.35rem', fontSize: '0.75rem', fontWeight: 700, color: '#b45309', background: '#fffbeb', padding: '0.4rem 0.75rem', borderRadius: '20px', border: '1px solid #fde68a' }}>
                  <span style={{ width: '6px', height: '6px', borderRadius: '50%', background: '#f59e0b' }} />
                  <span>{overallStats.booked} Booked</span>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.35rem', fontSize: '0.75rem', fontWeight: 700, color: '#b91c1c', background: '#fef2f2', padding: '0.4rem 0.75rem', borderRadius: '20px', border: '1px solid #fecaca' }}>
                  <span style={{ width: '6px', height: '6px', borderRadius: '50%', background: '#ef4444' }} />
                  <span>{overallStats.sold} Sold</span>
                </div>
              </div>
            </div>

            {/* Map canvas wrapper */}
            <div style={{ flex: 1, position: 'relative', overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
              {currentFloor?.imagePath ? (
                <ImagePlotMapView
                  imageSrc={currentFloor.imagePath.startsWith('http') || currentFloor.imagePath.startsWith('data:') || currentFloor.imagePath.startsWith('blob:') ? currentFloor.imagePath : `${import.meta.env.VITE_API_URL || ''}/uploads/${currentFloor.imagePath}`}
                  overlayConfig={layout?.overlayConfig?.byFloor?.[selectedFloorId] || {}}
                  plots={floorUnits}
                  selectedPlot={selectedUnit}
                  onSelectPlot={(p) => {
                    setSelectedUnit(p)
                    setActiveImageIdx(0)
                  }}
                  zoomPanEnabled={true}
                  useZoomLayout={true}
                  emptyMessage="No units calibrated on this floor layout."
                />
              ) : (
                <div style={{
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  justifyContent: 'center',
                  flex: 1,
                  minHeight: '400px',
                  padding: '3rem',
                  textAlign: 'center',
                  color: '#64748b',
                  background: '#fafafa'
                }}>
                  <span style={{ fontSize: '3rem', marginBottom: '1rem' }}>🗺️</span>
                  <h3 style={{ margin: 0, fontSize: '1.2rem', fontWeight: 800, color: '#0f172a' }}>No interactive layout uploaded</h3>
                  <p style={{ marginTop: '0.5rem', fontSize: '0.9rem', maxWidth: '320px', lineHeight: 1.5 }}>
                    This floor has no background floor plan map. Please inspect unit configurations in the details panel.
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* RIGHT SIDEBAR - Property Specs & Contact Panel */}
      <aside className="premium-buyer-sidebar custom-scrollbar">
        {selectedUnit ? (
          <div style={{ padding: '2.25rem 2rem', display: 'flex', flexDirection: 'column', gap: '1.75rem', flex: 1 }}>
            
            {/* Unit Info Header */}
            <div>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1rem' }}>
                <span style={{ fontSize: '0.75rem', fontWeight: 700, color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.12em' }}>
                  Unit {selectedUnit.number} · {layout?.name || 'Residence'}
                </span>
                <span className={`status-badge-luxury ${selectedUnit.status?.toLowerCase() || 'available'}`}>
                  {selectedUnit.status || 'Available'}
                </span>
              </div>
              <h2 style={{ fontSize: '1.8rem', fontWeight: 800, margin: '0.4rem 0 0 0', color: '#0f172a', letterSpacing: '-0.02em', lineHeight: 1.2 }}>
                {selectedUnit.beds || 2} BHK Residence
              </h2>
              {selectedUnit.description && (
                <p style={{ margin: '0.6rem 0 0 0', color: '#64748b', fontSize: '0.925rem', lineHeight: 1.55 }}>
                  {selectedUnit.description}
                </p>
              )}
            </div>

            {/* Spec grid specs */}
            <div className="property-specs-grid" style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(2, 1fr)',
              gap: '1.25rem',
              borderTop: '1px solid #f1f5f9',
              borderBottom: '1px solid #f1f5f9',
              padding: '1.5rem 0'
            }}>
              <div className="spec-item">
                <span className="spec-label">Carpet Area</span>
                <span className="spec-val">{selectedUnit.areaSqft || selectedUnit.area || 0} sq ft</span>
              </div>
              <div className="spec-item">
                <span className="spec-label">Area (Metric)</span>
                <span className="spec-val">{selectedUnit.areaSqm || ((selectedUnit.areaSqft || selectedUnit.area || 0) / 10.764).toFixed(1)} sq m</span>
              </div>
              <div className="spec-item">
                <span className="spec-label">Floor</span>
                <span className="spec-val">{currentFloor?.label || `Floor ${(currentFloor?.sortOrder ?? 0) + 1}`}</span>
              </div>
              <div className="spec-item">
                <span className="spec-label">Facing direction</span>
                <span className="spec-val">{selectedUnit.facing || 'East'}</span>
              </div>
            </div>

            {/* Pricing Section */}
            <div style={{
              background: 'linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%)',
              padding: '1.25rem 1.5rem',
              borderRadius: '16px',
              border: '1px solid #bbf7d0',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center'
            }}>
              <div>
                <span style={{ fontSize: '0.75rem', fontWeight: 700, color: '#166534', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                  Estimated Pricing
                </span>
                <div style={{ fontSize: '1.5rem', fontWeight: 800, color: '#14532d', marginTop: '0.2rem' }}>
                  {formatPrice(selectedUnit.estimatedPrice || (selectedUnit.areaSqft * selectedUnit.pricePerSqft) || selectedUnit.price)}
                </div>
              </div>
              {selectedUnit.pricePerSqft > 0 && (
                <div style={{ textAlign: 'right', fontSize: '0.8rem', color: '#166534', fontWeight: 600 }}>
                  {formatPrice(selectedUnit.pricePerSqft)} / sq ft
                </div>
              )}
            </div>

            {/* Carousel gallery images */}
            {selectedUnitMedia.images && selectedUnitMedia.images.length > 0 ? (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                <span style={{ fontSize: '0.8rem', fontWeight: 700, color: '#475569', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                  Residence Tour Gallery
                </span>
                
                {/* Main image view */}
                <div style={{
                  width: '100%',
                  height: '210px',
                  borderRadius: '16px',
                  overflow: 'hidden',
                  border: '1px solid #e2e8f0',
                  position: 'relative',
                  boxShadow: '0 4px 12px rgba(15, 23, 42, 0.02)'
                }}>
                  <img 
                    src={selectedUnitMedia.images[activeImageIdx] || selectedUnitMedia.images[0]} 
                    alt="Residence Preview" 
                    style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                  />
                  <div style={{
                    position: 'absolute',
                    bottom: 0,
                    left: 0,
                    right: 0,
                    background: 'linear-gradient(to top, rgba(0,0,0,0.5) 0%, transparent 100%)',
                    padding: '0.75rem 1rem',
                    color: '#ffffff',
                    fontSize: '0.8rem',
                    fontWeight: 600
                  }}>
                    Image {(activeImageIdx % selectedUnitMedia.images.length) + 1} of {selectedUnitMedia.images.length}
                  </div>
                </div>
                
                {/* Carousel Thumbnails */}
                <div style={{ display: 'flex', gap: '0.5rem', overflowX: 'auto', paddingBottom: '6px' }} className="carousel-thumbnails">
                  {selectedUnitMedia.images.map((img, idx) => (
                    <button
                      key={idx}
                      onClick={() => setActiveImageIdx(idx)}
                      style={{
                        padding: 0,
                        border: activeImageIdx === idx ? '2.5px solid #10b981' : '1px solid #cbd5e1',
                        width: '64px',
                        height: '48px',
                        borderRadius: '8px',
                        overflow: 'hidden',
                        cursor: 'pointer',
                        background: 'transparent',
                        flexShrink: 0
                      }}
                      className="thumbnail-btn"
                    >
                      <img src={img} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                    </button>
                  ))}
                </div>
              </div>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                <span style={{ fontSize: '0.8rem', fontWeight: 700, color: '#475569', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                  Residence Tour Gallery
                </span>
                <div style={{
                  width: '100%',
                  height: '210px',
                  borderRadius: '16px',
                  border: '2px dashed #cbd5e1',
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'center',
                  alignItems: 'center',
                  backgroundColor: '#f8fafc',
                  color: '#64748b',
                  textAlign: 'center',
                  padding: '1.5rem'
                }}>
                  <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#94a3b8" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" style={{ marginBottom: '0.5rem' }}>
                    <rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect>
                    <circle cx="8.5" cy="8.5" r="1.5"></circle>
                    <polyline points="21 15 16 10 5 21"></polyline>
                  </svg>
                  <div style={{ fontWeight: 600, fontSize: '0.95rem', marginBottom: '0.25rem', color: '#475569' }}>No Image Uploaded</div>
                  <div style={{ fontSize: '0.8rem', color: '#94a3b8' }}>Builder has not uploaded room images yet.</div>
                </div>
              </div>
            )}

            {/* Premium 3D Walkthrough CTA */}
            {selectedUnitMedia.rooms && selectedUnitMedia.rooms.length > 0 ? (
              <button
                onClick={() => setWalkthroughOpen(true)}
                className="premium-3d-button"
                style={{
                  width: '100%',
                  padding: '1.05rem',
                  background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
                  color: '#ffffff',
                  border: 'none',
                  borderRadius: '14px',
                  fontWeight: 700,
                  fontSize: '0.95rem',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: '0.6rem',
                  boxShadow: '0 6px 18px rgba(16, 185, 129, 0.22)',
                  transition: 'all 0.25s ease',
                  letterSpacing: '0.01em'
                }}
              >
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" style={{ transition: 'transform 0.3s ease' }}>
                  <polygon points="5 3 19 12 5 21 5 3"></polygon>
                </svg>
                EXPLORE 3D WALKTHROUGH
              </button>
            ) : (
              <button
                disabled
                style={{
                  width: '100%',
                  padding: '1.05rem',
                  background: '#f1f5f9',
                  color: '#94a3b8',
                  border: '1px solid #e2e8f0',
                  borderRadius: '14px',
                  fontWeight: 700,
                  fontSize: '0.95rem',
                  cursor: 'not-allowed',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: '0.6rem',
                  letterSpacing: '0.01em'
                }}
              >
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M10 15v4a3 3 0 0 0 3 3l4-9V2H5.72a2 2 0 0 0-2 1.7l-1.38 9a2 2 0 0 0 2 2.3zm7-13h2.67A2.31 2.31 0 0 1 22 4v7a2.31 2.31 0 0 1-2.33 2H17"></path>
                </svg>
                360° VIEW NOT AVAILABLE
              </button>
            )}

            {/* Builder profile details */}
            <div style={{
              background: '#f8fafc',
              border: '1px solid #e2e8f0',
              borderRadius: '18px',
              padding: '1.25rem',
              display: 'flex',
              flexDirection: 'column',
              gap: '1rem',
              marginTop: 'auto'
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                {layout?.owner?.logoPath ? (
                  <img
                    src={`${apiBase}/uploads/${layout.owner.logoPath}`}
                    alt="Builder Logo"
                    style={{
                      width: '42px',
                      height: '42px',
                      borderRadius: '12px',
                      objectFit: 'contain',
                      border: '1px solid #e2e8f0',
                      background: '#ffffff'
                    }}
                  />
                ) : (
                  <div style={{
                    width: '42px',
                    height: '42px',
                    borderRadius: '12px',
                    background: '#ecfdf5',
                    color: '#10b981',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: '1.25rem',
                    fontWeight: 800,
                    border: '1px solid #a7f3d0'
                  }}>
                    {builderName.charAt(0)}
                  </div>
                )}
                <div>
                  <h4 style={{ margin: 0, fontSize: '0.925rem', fontWeight: 800, color: '#0f172a' }}>
                    {builderName}
                  </h4>
                  <p style={{ margin: '2px 0 0 0', fontSize: '0.75rem', color: '#64748b', fontWeight: 600 }}>
                    {companyName}
                  </p>
                </div>
              </div>

              {(builderExperience != null || builderProjects != null) && (
                <div style={{ borderTop: '1px solid #e2e8f0', paddingTop: '10px', display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '8px', fontSize: '0.75rem' }}>
                  {builderExperience != null && (
                    <div>
                      <span style={{ color: '#94a3b8', display: 'block', fontWeight: 600 }}>Experience</span>
                      <span style={{ fontWeight: 700, color: '#475569' }}>{builderExperience} Years</span>
                    </div>
                  )}
                  {builderProjects != null && (
                    <div>
                      <span style={{ color: '#94a3b8', display: 'block', fontWeight: 600 }}>Projects</span>
                      <span style={{ fontWeight: 700, color: '#475569' }}>{builderProjects} Delivered</span>
                    </div>
                  )}
                </div>
              )}
              {builderRera && (
                <div style={{ fontSize: '0.7rem', color: '#64748b', background: '#ffffff', padding: '6px 10px', borderRadius: '6px', border: '1px solid #e2e8f0' }}>
                  RERA: <span style={{ fontWeight: 700, color: '#334155' }}>{builderRera}</span>
                </div>
              )}

              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.5rem' }}>
                <a 
                  href={`https://wa.me/${builderWhatsapp}`} 
                  target="_blank" 
                  rel="noreferrer" 
                  className="builder-btn-wa"
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '0.4rem',
                    padding: '0.55rem 0.5rem',
                    borderRadius: '10px',
                    background: '#25D366',
                    color: '#ffffff',
                    fontWeight: 700,
                    fontSize: '0.8rem',
                    textDecoration: 'none',
                    boxShadow: '0 2px 4px rgba(37, 211, 102, 0.12)',
                    transition: 'all 0.2s ease'
                  }}
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg>
                  WhatsApp
                </a>
                <a 
                  href={`tel:${builderPhone}`} 
                  className="builder-btn-call"
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '0.4rem',
                    padding: '0.55rem 0.5rem',
                    borderRadius: '10px',
                    background: '#ffffff',
                    color: '#0f172a',
                    fontWeight: 700,
                    fontSize: '0.8rem',
                    textDecoration: 'none',
                    border: '1px solid #cbd5e1',
                    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.01)',
                    transition: 'all 0.2s ease'
                  }}
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>
                  Call
                </a>
              </div>

              {selectedUnit?.status === 'Sold' || selectedUnit?.status === 'Booked' ? (
                <div style={{
                  padding: '0.8rem',
                  border: `1px solid ${selectedUnit.status === 'Sold' ? '#fecaca' : '#fde68a'}`,
                  borderRadius: '10px',
                  background: selectedUnit.status === 'Sold' ? '#fef2f2' : '#fffbeb',
                  color: selectedUnit.status === 'Sold' ? '#ef4444' : '#d97706',
                  fontWeight: 700,
                  fontSize: '0.825rem',
                  textAlign: 'center',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: '0.4rem'
                }}>
                  🔒 This unit is {selectedUnit.status}
                </div>
              ) : (
                <button
                  onClick={() => setInterestModalOpen(true)}
                  className="builder-btn-interest"
                  style={{
                    padding: '0.7rem',
                    border: '1px solid #10b981',
                    borderRadius: '10px',
                    background: '#ecfdf5',
                    color: '#059669',
                    fontWeight: 700,
                    fontSize: '0.825rem',
                    cursor: 'pointer',
                    transition: 'all 0.2s ease',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '0.4rem'
                  }}
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg>
                  Book / Call Back Request
                </button>
              )}
            </div>

          </div>
        ) : (
          /* Empty Details State - Render curated project brochure summary */
          <div style={{ padding: '2.5rem 2rem', display: 'flex', flexDirection: 'column', gap: '2rem', height: '100%', overflowY: 'auto' }} className="custom-scrollbar">
            {currentStep === 'facade' ? (
              <>
                <div>
                  <span style={{
                    fontSize: '0.75rem',
                    fontWeight: 700,
                    color: '#10b981',
                    textTransform: 'uppercase',
                    letterSpacing: '0.15em',
                    display: 'inline-block',
                    marginBottom: '0.5rem'
                  }}>
                    Interactive Explorer
                  </span>
                  <h2 style={{ fontSize: '1.8rem', fontWeight: 800, margin: 0, color: '#0f172a', letterSpacing: '-0.02em', lineHeight: 1.25 }}>
                    Explore Residences
                  </h2>
                </div>

                <div style={{
                  background: '#f8fafc',
                  border: '1px dashed #cbd5e1',
                  borderRadius: '24px',
                  padding: '2.5rem 1.5rem',
                  textAlign: 'center',
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: '1rem',
                  color: '#475569'
                }}>
                  <span style={{ fontSize: '2.5rem' }}>🏢</span>
                  <p style={{ margin: 0, fontSize: '0.925rem', fontWeight: 600, lineHeight: 1.6, color: '#475569' }}>
                    Select a floor on the building model or choose from the list to view blueprints, check unit availability, and view 3D walkthrough tours.
                  </p>
                </div>
              </>
            ) : (
              <>
                <div>
                  <span style={{
                    fontSize: '0.75rem',
                    fontWeight: 700,
                    color: '#10b981',
                    textTransform: 'uppercase',
                    letterSpacing: '0.15em',
                    display: 'inline-block',
                    marginBottom: '0.5rem'
                  }}>
                    Project Overview
                  </span>
                  <h2 style={{ fontSize: '1.8rem', fontWeight: 800, margin: 0, color: '#0f172a', letterSpacing: '-0.02em', lineHeight: 1.25 }}>
                    Building Summary
                  </h2>
                </div>

                {/* Overall Statistics Summary Card */}
                <div style={{
                  background: '#ffffff',
                  borderRadius: '24px',
                  border: '1px solid #e2e8f0',
                  padding: '1.5rem',
                  boxShadow: '0 4px 15px rgba(15, 23, 42, 0.02)',
                  display: 'flex',
                  flexDirection: 'column',
                  gap: '1.25rem'
                }}>
                  <h4 style={{ margin: 0, fontSize: '0.8rem', fontWeight: 800, color: '#475569', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
                    Availability Chart
                  </h4>

                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.75rem' }}>
                    <div style={{ background: '#f8fafc', padding: '1rem', borderRadius: '14px', display: 'flex', flexDirection: 'column', gap: '0.2rem' }}>
                      <span style={{ fontSize: '0.75rem', color: '#64748b', fontWeight: 600 }}>Total Units</span>
                      <span style={{ fontSize: '1.5rem', fontWeight: 800, color: '#0f172a' }}>{overallStats.total}</span>
                    </div>
                    <div style={{ background: '#ecfdf5', padding: '1rem', borderRadius: '14px', display: 'flex', flexDirection: 'column', gap: '0.2rem' }}>
                      <span style={{ fontSize: '0.75rem', color: '#047857', fontWeight: 600 }}>Available</span>
                      <span style={{ fontSize: '1.5rem', fontWeight: 800, color: '#059669' }}>{overallStats.available}</span>
                    </div>
                    <div style={{ background: '#fffbeb', padding: '1rem', borderRadius: '14px', display: 'flex', flexDirection: 'column', gap: '0.2rem' }}>
                      <span style={{ fontSize: '0.75rem', color: '#b45309', fontWeight: 600 }}>Booked</span>
                      <span style={{ fontSize: '1.5rem', fontWeight: 800, color: '#d97706' }}>{overallStats.booked}</span>
                    </div>
                    <div style={{ background: '#fef2f2', padding: '1rem', borderRadius: '14px', display: 'flex', flexDirection: 'column', gap: '0.2rem' }}>
                      <span style={{ fontSize: '0.75rem', color: '#b91c1c', fontWeight: 600 }}>Sold</span>
                      <span style={{ fontSize: '1.5rem', fontWeight: 800, color: '#dc2626' }}>{overallStats.sold}</span>
                    </div>
                  </div>
                </div>

                {/* Info Interactive prompt */}
                <div style={{
                  background: '#f8fafc',
                  border: '1px dashed #cbd5e1',
                  borderRadius: '24px',
                  padding: '2rem 1.5rem',
                  textAlign: 'center',
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: '1rem',
                  color: '#475569'
                }}>
                  <span style={{ fontSize: '2.5rem', animation: 'bounce 2.5s infinite' }}>🗺️</span>
                  <p style={{ margin: 0, fontSize: '0.925rem', fontWeight: 600, lineHeight: 1.6, color: '#475569' }}>
                    Select any unit on the interactive floor map to explore floor dimensions, estimated pricing, 360° tour galleries, 3D walkthroughs, and check real-time availability.
                  </p>
                </div>
              </>
            )}

            {/* Builder Contact Card for general query */}
            <div style={{
              background: '#f8fafc',
              border: '1px solid #e2e8f0',
              borderRadius: '18px',
              padding: '1.25rem',
              display: 'flex',
              flexDirection: 'column',
              gap: '1rem',
              marginTop: 'auto'
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                {layout?.owner?.logoPath ? (
                  <img
                    src={`${apiBase}/uploads/${layout.owner.logoPath}`}
                    alt="Builder Logo"
                    style={{
                      width: '42px',
                      height: '42px',
                      borderRadius: '12px',
                      objectFit: 'contain',
                      border: '1px solid #e2e8f0',
                      background: '#ffffff'
                    }}
                  />
                ) : (
                  <div style={{
                    width: '42px',
                    height: '42px',
                    borderRadius: '12px',
                    background: '#ecfdf5',
                    color: '#10b981',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: '1.25rem',
                    fontWeight: 800,
                    border: '1px solid #a7f3d0'
                  }}>
                    {builderName.charAt(0)}
                  </div>
                )}
                <div>
                  <h4 style={{ margin: 0, fontSize: '0.925rem', fontWeight: 800, color: '#0f172a' }}>
                    {builderName}
                  </h4>
                  <p style={{ margin: '2px 0 0 0', fontSize: '0.75rem', color: '#64748b', fontWeight: 600 }}>
                    {companyName}
                  </p>
                </div>
              </div>

              {(builderExperience != null || builderProjects != null) && (
                <div style={{ borderTop: '1px solid #e2e8f0', paddingTop: '10px', display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '8px', fontSize: '0.75rem' }}>
                  {builderExperience != null && (
                    <div>
                      <span style={{ color: '#94a3b8', display: 'block', fontWeight: 600 }}>Experience</span>
                      <span style={{ fontWeight: 700, color: '#475569' }}>{builderExperience} Years</span>
                    </div>
                  )}
                  {builderProjects != null && (
                    <div>
                      <span style={{ color: '#94a3b8', display: 'block', fontWeight: 600 }}>Projects</span>
                      <span style={{ fontWeight: 700, color: '#475569' }}>{builderProjects} Delivered</span>
                    </div>
                  )}
                </div>
              )}
              {builderRera && (
                <div style={{ fontSize: '0.7rem', color: '#64748b', background: '#ffffff', padding: '6px 10px', borderRadius: '6px', border: '1px solid #e2e8f0' }}>
                  RERA: <span style={{ fontWeight: 700, color: '#334155' }}>{builderRera}</span>
                </div>
              )}

              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.5rem' }}>
                <a href={`https://wa.me/${builderWhatsapp}`} target="_blank" rel="noreferrer" className="builder-btn-wa" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.4rem', padding: '0.55rem 0.5rem', borderRadius: '10px', background: '#25D366', color: '#ffffff', fontWeight: 700, fontSize: '0.8rem', textDecoration: 'none', boxShadow: '0 2px 4px rgba(37, 211, 102, 0.12)', transition: 'all 0.2s ease' }}>
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg>
                  WhatsApp
                </a>
                <a href={`tel:${builderPhone}`} className="builder-btn-call" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.4rem', padding: '0.55rem 0.5rem', borderRadius: '10px', background: '#ffffff', color: '#0f172a', fontWeight: 700, fontSize: '0.8rem', textDecoration: 'none', border: '1px solid #cbd5e1', boxShadow: '0 2px 4px rgba(0, 0, 0, 0.01)', transition: 'all 0.2s ease' }}>
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>
                  Call
                </a>
              </div>
            </div>
          </div>
        )}
      </aside>

      {/* 3D virtual tour overlay modal */}
      {walkthroughOpen && selectedUnit && (
        <Custom3DWalkthrough 
          rooms={selectedUnitMedia.rooms}
          defaultRoomId={selectedUnitMedia.rooms[0]?.id}
          onClose={() => setWalkthroughOpen(false)}
        />
      )}

      {/* White Glassmorphism booking modal */}
      {interestModalOpen && selectedUnit && (
        <div style={{
          position: 'fixed',
          inset: 0,
          background: 'rgba(15, 23, 42, 0.3)',
          backdropFilter: 'blur(8px)',
          WebkitBackdropFilter: 'blur(8px)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 3000,
          animation: 'fade-in 0.25s ease-out'
        }}>
          <div style={{
            background: 'rgba(255, 255, 255, 0.85)',
            backdropFilter: 'blur(20px)',
            WebkitBackdropFilter: 'blur(20px)',
            border: '1px solid rgba(255, 255, 255, 0.4)',
            borderRadius: '24px',
            padding: '2.5rem',
            width: '90%',
            maxWidth: '430px',
            position: 'relative',
            boxShadow: '0 25px 50px -12px rgba(15, 23, 42, 0.15)',
            animation: 'scale-up 0.3s cubic-bezier(0.16, 1, 0.3, 1)'
          }}>
            {/* Close Button */}
            <button 
              onClick={() => setInterestModalOpen(false)}
              style={{
                position: 'absolute',
                top: '20px',
                right: '20px',
                background: 'rgba(15, 23, 42, 0.05)',
                border: 'none',
                color: '#0f172a',
                width: '32px',
                height: '32px',
                borderRadius: '50%',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '1.2rem',
                cursor: 'pointer',
                transition: 'all 0.2s ease'
              }}
              onMouseEnter={(e) => e.currentTarget.style.background = 'rgba(15, 23, 42, 0.1)'}
              onMouseLeave={(e) => e.currentTarget.style.background = 'rgba(15, 23, 42, 0.05)'}
            >
              ×
            </button>
            
            <div style={{ textAlign: 'center', marginBottom: '1.75rem' }}>
              <span style={{
                fontSize: '2rem',
                display: 'inline-block',
                marginBottom: '0.75rem',
                animation: 'bounce 2s infinite'
              }}>
                🔑
              </span>
              <h3 style={{ margin: 0, fontSize: '1.5rem', fontWeight: 800, color: '#0f172a', letterSpacing: '-0.01em' }}>
                Request Booking Details
              </h3>
              <p style={{ margin: '0.4rem 0 0 0', fontSize: '0.875rem', color: '#64748b', fontWeight: 600 }}>
                Unit {selectedUnit.number} · Floor {currentFloor?.label || '1'}
              </p>
            </div>

            <form onSubmit={handleLeadSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
              {leadError && (
                <div style={{
                  color: '#dc2626',
                  fontSize: '0.85rem',
                  background: '#fef2f2',
                  padding: '0.75rem 1rem',
                  borderRadius: '12px',
                  border: '1px solid #fecaca',
                  fontWeight: 600
                }}>
                  ⚠️ {leadError}
                </div>
              )}
              
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
                <label style={{ fontSize: '0.75rem', fontWeight: 700, color: '#475569', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Full Name</label>
                <input 
                  type="text" 
                  placeholder="Enter your name" 
                  value={customerName}
                  onChange={(e) => setCustomerName(e.target.value)}
                  style={{
                    padding: '0.85rem 1rem',
                    borderRadius: '12px',
                    border: '1px solid #e2e8f0',
                    background: '#ffffff',
                    color: '#0f172a',
                    outline: 'none',
                    fontSize: '0.95rem',
                    transition: 'all 0.2s ease',
                    boxShadow: 'inset 0 1px 2px rgba(0,0,0,0.02)'
                  }}
                  onFocus={(e) => {
                    e.currentTarget.style.borderColor = '#10b981'
                    e.currentTarget.style.boxShadow = '0 0 0 3px rgba(16, 185, 129, 0.15)'
                  }}
                  onBlur={(e) => {
                    e.currentTarget.style.borderColor = '#e2e8f0'
                    e.currentTarget.style.boxShadow = 'inset 0 1px 2px rgba(0,0,0,0.02)'
                  }}
                  required
                />
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
                <label style={{ fontSize: '0.75rem', fontWeight: 700, color: '#475569', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Phone Number</label>
                <input 
                  type="tel" 
                  placeholder="Enter contact number" 
                  value={contactNumber}
                  onChange={(e) => setContactNumber(e.target.value)}
                  style={{
                    padding: '0.85rem 1rem',
                    borderRadius: '12px',
                    border: '1px solid #e2e8f0',
                    background: '#ffffff',
                    color: '#0f172a',
                    outline: 'none',
                    fontSize: '0.95rem',
                    transition: 'all 0.2s ease',
                    boxShadow: 'inset 0 1px 2px rgba(0,0,0,0.02)'
                  }}
                  onFocus={(e) => {
                    e.currentTarget.style.borderColor = '#10b981'
                    e.currentTarget.style.boxShadow = '0 0 0 3px rgba(16, 185, 129, 0.15)'
                  }}
                  onBlur={(e) => {
                    e.currentTarget.style.borderColor = '#e2e8f0'
                    e.currentTarget.style.boxShadow = 'inset 0 1px 2px rgba(0,0,0,0.02)'
                  }}
                  required
                />
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
                <label style={{ fontSize: '0.75rem', fontWeight: 700, color: '#475569', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Email Address</label>
                <input 
                  type="email" 
                  placeholder="Enter email address" 
                  value={customerEmail}
                  onChange={(e) => setCustomerEmail(e.target.value)}
                  style={{
                    padding: '0.85rem 1rem',
                    borderRadius: '12px',
                    border: '1px solid #e2e8f0',
                    background: '#ffffff',
                    color: '#0f172a',
                    outline: 'none',
                    fontSize: '0.95rem',
                    transition: 'all 0.2s ease',
                    boxShadow: 'inset 0 1px 2px rgba(0,0,0,0.02)'
                  }}
                  onFocus={(e) => {
                    e.currentTarget.style.borderColor = '#10b981'
                    e.currentTarget.style.boxShadow = '0 0 0 3px rgba(16, 185, 129, 0.15)'
                  }}
                  onBlur={(e) => {
                    e.currentTarget.style.borderColor = '#e2e8f0'
                    e.currentTarget.style.boxShadow = 'inset 0 1px 2px rgba(0,0,0,0.02)'
                  }}
                  required
                />
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
                <label style={{ fontSize: '0.75rem', fontWeight: 700, color: '#475569', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Message / Requirements</label>
                <textarea 
                  placeholder="Enter your message or requirements" 
                  value={customerMessage}
                  onChange={(e) => setCustomerMessage(e.target.value)}
                  rows={3}
                  style={{
                    padding: '0.85rem 1rem',
                    borderRadius: '12px',
                    border: '1px solid #e2e8f0',
                    background: '#ffffff',
                    color: '#0f172a',
                    outline: 'none',
                    fontSize: '0.95rem',
                    transition: 'all 0.2s ease',
                    boxShadow: 'inset 0 1px 2px rgba(0,0,0,0.02)',
                    fontFamily: 'inherit',
                    resize: 'vertical'
                  }}
                  onFocus={(e) => {
                    e.currentTarget.style.borderColor = '#10b981'
                    e.currentTarget.style.boxShadow = '0 0 0 3px rgba(16, 185, 129, 0.15)'
                  }}
                  onBlur={(e) => {
                    e.currentTarget.style.borderColor = '#e2e8f0'
                    e.currentTarget.style.boxShadow = 'inset 0 1px 2px rgba(0,0,0,0.02)'
                  }}
                />
              </div>

              <button 
                type="submit" 
                disabled={submittingLead}
                style={{
                  padding: '1rem',
                  borderRadius: '14px',
                  background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
                  color: '#ffffff',
                  border: 'none',
                  fontWeight: 700,
                  fontSize: '0.975rem',
                  cursor: 'pointer',
                  marginTop: '0.5rem',
                  transition: 'all 0.2s ease',
                  boxShadow: '0 4px 12px rgba(16, 185, 129, 0.2)'
                }}
              >
                {submittingLead ? 'Submitting...' : 'Submit Request'}
              </button>
            </form>
          </div>
        </div>
      )}

      {/* Glassmorphic Top Toast success notification */}
      {submitted && (
        <div style={{
          position: 'fixed',
          top: '24px',
          left: '50%',
          transform: 'translateX(-50%)',
          zIndex: 3100,
          background: 'rgba(255, 255, 255, 0.9)',
          backdropFilter: 'blur(12px)',
          WebkitBackdropFilter: 'blur(12px)',
          color: '#0f172a',
          padding: '1.25rem 2.25rem',
          borderRadius: '20px',
          boxShadow: '0 20px 40px rgba(16, 185, 129, 0.12), 0 1px 3px rgba(0, 0, 0, 0.05)',
          border: '1px solid rgba(16, 185, 129, 0.3)',
          display: 'flex',
          alignItems: 'center',
          gap: '1rem',
          fontWeight: '600',
          animation: 'slide-down 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards'
        }}>
          <span style={{
            width: '28px',
            height: '28px',
            borderRadius: '50%',
            background: '#ecfdf5',
            color: '#10b981',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            fontSize: '1rem',
            fontWeight: 'bold',
            boxShadow: '0 2px 4px rgba(16, 185, 129, 0.2)'
          }}>
            ✓
          </span>
          <span style={{ fontSize: '0.95rem' }}>Interest submitted successfully! We will contact you soon.</span>
          <button 
            onClick={() => setSubmitted(false)}
            style={{
              background: 'none',
              border: 'none',
              color: '#64748b',
              cursor: 'pointer',
              fontWeight: 700,
              fontSize: '1.1rem',
              padding: '0 0 0 0.5rem',
              transition: 'color 0.2s'
            }}
            onMouseEnter={(e) => e.currentTarget.style.color = '#0f172a'}
            onMouseLeave={(e) => e.currentTarget.style.color = '#64748b'}
          >
            ×
          </button>
        </div>
      )}

    </div>
  )
}
